# Generated by Django 6.0 on 2025-12-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='media/profile_pic/default.png', upload_to='prfile_pic/'),
        ),
    ]
